# I have no idea what I'm doing
name: Automatic Build

on:
  push:
    branches: ['dev', 'autobuild']
    paths-ignore: ['*.md', '*.json', '*.png']
  pull_request:
    branches: ['dev', 'autobuild']
    paths-ignore: ['*.md', '*.json', '*.png']
  workflow_dispatch:

jobs:

  build-libretro-stage1:
    name: LR stage 1
    runs-on: ubuntu-latest
    outputs:
      sha: ${{ steps.short-sha.outputs.sha }}
      artifact-id: ${{ steps.upload-artifact.outputs.artifact-id }}
    steps:
      - name: Expose Actions environment
        uses: white-axe/expose-actions-environment@v1

      - name: Checkout repository
        uses: taiki-e/checkout-action@v1

      - id: short-sha
        name: Get Git commit hash
        run: |
          sha=$(git rev-parse --short=7 HEAD)
          echo "sha=$sha" >> "$GITHUB_OUTPUT"

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y git curl build-essential automake libtool zip universal-ctags ruby nodejs npm
          npm install @actions/artifact@4 fast-glob@3

      - name: Set up WASI SDK
        run: |
          curl -Lo ${{ runner.temp }}/wasi-sdk.tar.gz https://github.com/WebAssembly/wasi-sdk/releases/download/wasi-sdk-29/wasi-sdk-29.0-x86_64-linux.tar.gz
          mkdir ${{ runner.temp }}/wasi-sdk
          tar -xzf ${{ runner.temp }}/wasi-sdk.tar.gz -C ${{ runner.temp }}/wasi-sdk --strip-components=1
          rm ${{ runner.temp }}/wasi-sdk.tar.gz

      - name: Set up Binaryen
        run: |
          curl -Lo ${{ runner.temp }}/binaryen.tar.gz https://github.com/WebAssembly/binaryen/releases/download/version_125/binaryen-version_125-x86_64-linux.tar.gz
          mkdir ${{ runner.temp }}/binaryen
          tar -xzf ${{ runner.temp }}/binaryen.tar.gz -C ${{ runner.temp }}/binaryen --strip-components=1
          rm ${{ runner.temp }}/binaryen.tar.gz

      - name: Build stage 1
        run: |
          cd libretro
          CLICOLOR_FORCE=1 make -j $(nproc) WASI_SDK=${{ runner.temp }}/wasi-sdk WASM_OPT=${{ runner.temp }}/binaryen/bin/wasm-opt

      - id: upload-artifact
        name: Upload artifact
        run: |
          node --input-type=module -e '
            import {DefaultArtifactClient} from "@actions/artifact";
            import fg from "fast-glob";
            import fs from "fs";
            process.chdir("libretro/build/libretro-stage1");
            const artifact = new DefaultArtifactClient();
            const {id, size} = await artifact.uploadArtifact(
              "stage1.${{ github.event_name == 'pull_request' && format('PR{0}', github.event.number) || github.ref_name }}-${{ steps.short-sha.outputs.sha }}",
              fg.globSync("**"),
              ".",
            );
            fs.appendFileSync(process.env.GITHUB_OUTPUT, `artifact-id=${id}`);
          '


  build-libretro-darwin:
    needs: build-libretro-stage1
    name: LR ${{ matrix.system_name }} ${{ matrix.arch_mkxpz }}
    runs-on: macos-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - system_name: iOS
            system_mkxpz: ios
            sdk: iphoneos
            suffix: _ios
            arch_mkxpz: arm64
            arch_llvm: arm64-apple-ios10.0 # iOS 10 is the first version of iOS with support for 64-bit ARM
            cpu_family: aarch64
            cpu: generic-armv8-a
            endian: little
    steps:
      - name: Expose Actions environment
        uses: crazy-max/ghaction-github-runtime@v3

      - name: Install dependencies
        run: |
          brew uninstall -f --ignore-dependencies git meson cmake node
          brew install -q git meson cmake node
          npm install @actions/artifact@4 fast-glob@3

      - name: Checkout repository
        uses: taiki-e/checkout-action@v1

      - name: Download stage 1
        run: |
          node --input-type=module -e '
            import {DefaultArtifactClient} from "@actions/artifact";
            const artifact = new DefaultArtifactClient();
            await artifact.downloadArtifact(${{ needs.build-libretro-stage1.outputs.artifact-id }}, {
              path: "libretro/build/libretro-stage1",
            });
          '

      - name: Configure core
        run: |
          echo "[binaries]" | tee -a ${{ runner.temp }}/cross.ini
          echo "c = ['xcrun', '--sdk', '${{ matrix.sdk }}', 'clang', '--target=${{ matrix.arch_llvm }}']" | tee -a ${{ runner.temp }}/cross.ini
          echo "cpp = ['xcrun', '--sdk', '${{ matrix.sdk }}', 'clang++', '--target=${{ matrix.arch_llvm }}']" | tee -a ${{ runner.temp }}/cross.ini
          echo "ar = 'ar'" | tee -a ${{ runner.temp }}/cross.ini
          echo "strip = 'strip'" | tee -a ${{ runner.temp }}/cross.ini
          echo "[host_machine]" | tee -a ${{ runner.temp }}/cross.ini
          echo "system = 'darwin'" | tee -a ${{ runner.temp }}/cross.ini
          echo "cpu_family = '${{ matrix.cpu_family }}'" | tee -a ${{ runner.temp }}/cross.ini
          echo "cpu = '${{ matrix.cpu }}'" | tee -a ${{ runner.temp }}/cross.ini
          echo "endian = '${{ matrix.endian }}'" | tee -a ${{ runner.temp }}/cross.ini
          echo "[cmake]" | tee -a ${{ runner.temp }}/cross.ini
          echo "CMAKE_OSX_SYSROOT = '/nonexistent'" | tee -a ${{ runner.temp }}/cross.ini
          echo '--------------------------------------------------------------------------------'
          CLICOLOR_FORCE=1 meson setup build --cross-file ${{ runner.temp }}/cross.ini --buildtype release -Db_lto=true -Dlibretro=true -Dlibretro_save_states=true

      - name: Build core
        run: |
          mkdir ${{ runner.temp }}/dist
          cd build
          CLICOLOR_FORCE=1 ninja -v
          strip -x mkxp-z_libretro.dylib
          mv mkxp-z_libretro.dylib ${{ runner.temp }}/dist/mkxp-z_libretro${{ matrix.suffix }}.dylib

      - name: Upload artifact
        run: |
          node --input-type=module -e '
            import {DefaultArtifactClient} from "@actions/artifact";
            import fg from "fast-glob";
            process.chdir("${{ runner.temp }}/dist");
            const artifact = new DefaultArtifactClient();
            await artifact.uploadArtifact(
              "mkxp-z_libretro.${{ matrix.system_mkxpz }}.${{ matrix.arch_mkxpz }}.${{ github.event_name == 'pull_request' && format('PR{0}', github.event.number) || github.ref_name }}-${{ needs.build-libretro-stage1.outputs.sha }}",
              fg.globSync("**"),
              ".",
            );
          '

